import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full grid grid-rows-[1fr_1fr_1fr]`}>
        <header className="row-span-1 bg-blue-500 fixed top-0 w-full  text-center p-2 text-slate-100 z-100 ">2026 FRC Scouting App Header
         <Header />
        </header>
        <main className=" grid grid-rows-[auto_1fr] min-h-screen bg-black h-full">{children}</main>
        <footer className="row-span-1 bg-blue-500 fixed bottom-0 w-full text-center p-2 text-slate-100 z-100 ">2026 FRC Scouting App Footer
        </footer>
        
      </body>
</html>
  );
}
