import mongoose from "mongoose";

export interface IMatchSummary {
    scoutKey: string,
    eventCode: string,
    tournamentLevel: string,
    matchNumber: number,
    teamNumber: string,
    AutoClimb: number,
    Endgame: number,
    Teleop: number,
    Total: number,
    AutoFuel: number,
    FirstShiftFuel: number,
    SecondShiftFuel: number,
    EndgameFuel: number,
    TeleopFuel: number,
    TotalFuel: number,
    UncountedFuel: number,
    scouted: boolean,
    autoLaunches: number,
    firstShiftLauches: number,
    secondShiftLauches: number,
    endgameLaunches: number,
    robotDied: number,
    robotBroke: number,
    passHeard: number,
    passLaunched: number,
    autoAJDFuel: number,
    autoAlone: boolean,
    firstShiftAJDFuel: number,
    firstShiftAlone: boolean,
    secondShiftAJDFuel: number,
    secondShiftAlone: boolean,
    endgameAJDFuel: number,
    endgameAlone: boolean,
    totalADJFuel: number,
    totalLaunches: number,
    totalAloneSifts: number,
    totalAloneSiftFuel: number,
    totalAloneSiftLaunches: number,
    //meta data for the file. 
    createdAt: Date,
    updatedAt: Date,
  
}

export const MatchSummarySchema = new mongoose.Schema<IMatchSummary>(
{
    scoutKey: {
        type: String,
        required: true,
        unique: true,
    },
    eventCode: { type: String, },
    tournamentLevel: { type: String, },
    matchNumber: { type: Number, },
    teamNumber: { type: String, },
    AutoClimb: { type: Number, },
    Endgame: { type: Number, },
    Teleop: { type: Number, },
    Total: { type: Number, },
    AutoFuel: { type: Number, },
    FirstShiftFuel: { type: Number, },
    SecondShiftFuel: { type: Number, },
    EndgameFuel: { type: Number, },
    TeleopFuel: { type: Number, },
    TotalFuel: { type: Number, },
    UncountedFuel: { type: Number, },
    scouted: { type: Boolean, },
    autoLaunches: { type: Number, },
    firstShiftLauches: { type: Number, },
    secondShiftLauches: { type: Number, },
    endgameLaunches: { type: Number, },
    robotDied: { type: Number, },
    robotBroke: { type: Number, },
    passHeard: { type: Number, },
    passLaunched: { type: Number, },
    autoAJDFuel: { type: Number, },
    autoAlone: { type: Boolean, },
    firstShiftAJDFuel: { type: Number, },
    firstShiftAlone: { type: Boolean, },
    secondShiftAJDFuel: { type: Number, },
    secondShiftAlone: { type: Boolean, },
    endgameAJDFuel: { type: Number, },
    endgameAlone: { type: Boolean, },
    totalADJFuel: { type: Number, },
    totalLaunches: { type: Number, },
    totalAloneSifts: { type: Number, },
    totalAloneSiftFuel: { type: Number, },
    totalAloneSiftLaunches: { type: Number, },
    createdAt: { type: Date, default: Date.now, },
    updatedAt: { type: Date, default: Date.now, },
  },
);

const MatchSummary = mongoose.models?.MatchSummary || mongoose.model<IMatchSummary>("MatchSummary", MatchSummarySchema);

export default MatchSummary;