import mongoose from "mongoose";

export interface IMatchSummary {
    summaryID: string,
    teamNumber: number,
    eventCode: string,
    tournamentLevel: string,
    matchNumber: string,
    autoClimb: string,
    endgameClimb: string,
    autoOnlyFuel: number,
    autoFuel: number,
    firstShiftFuel: number,
    secondShiftFuel: number,
    endgameFuel: number,
    totalFuel: number,
    adjAutoFuel: number,
    adjFirstShiftFuel: number,
    adjSecondShiftFuel: number,
    adjEndgameFuel: number,
    totalAdjFuel: number,
    allianceScouted: boolean,
    scoutedData: {
      teamNumber: string,
      autoLaunches: number,
      firstShiftLauches: number,
      secondShiftLauches: number,
      endgameLaunches: number,
      passHerdNeutral: number,
      passHerdOpposing: number,
      passLaunchedNeutral: number,
      passLaunchedOpposing: number,
      defenseNeutral: number,
      defenseOpposing: number,
      robotDied: number,
      robotBroke: number
    },
    autoDenominator: number,
    firstShiftDenominator: number,
    secondShiftDenominator: number,
    endgameDenominator: number,
    //meta data for the file. 
    createdAt?: Date,
    updatedAt?: Date,
  
}

export const MatchSummarySchema = new mongoose.Schema<IMatchSummary>(
{
    summaryID: {
        type: String,
        required: true,
        unique: true,
    },
    teamNumber: { type: Number, },
    eventCode: { type: String, },
    tournamentLevel: { type: String, },
    matchNumber: { type: String, },
    autoClimb: { type: String, },
    endgameClimb: { type: String, },
    autoOnlyFuel: { type: Number, },
    autoFuel: { type: Number, },
    firstShiftFuel: { type: Number, },
    secondShiftFuel: { type: Number, },
    endgameFuel: { type: Number, },
    totalFuel: { type: Number, },
    adjAutoFuel: { type: Number, },
    adjFirstShiftFuel: { type: Number, },
    adjSecondShiftFuel: { type: Number, },
    adjEndgameFuel: { type: Number, },
    totalAdjFuel: { type: Number, },
    allianceScouted: { type: Boolean, },
    scoutedData: {
      teamNumber: { type: String, },
      autoLaunches: { type: Number, },
      firstShiftLauches: { type: Number, },
      secondShiftLauches: { type: Number, },
      endgameLaunches: { type: Number, },
      passHerdNeutral: { type: Number, },
      passHerdOpposing: { type: Number, },
      passLaunchedNeutral: { type: Number, },
      passLaunchedOpposing: { type: Number, },
      defenseNeutral: { type: Number, },
      defenseOpposing: { type: Number, },
      robotDied: { type: Number, },
      robotBroke: { type: Number, },
    },
    autoDenominator: { type: Number, },
    firstShiftDenominator: { type: Number, },
    secondShiftDenominator: { type: Number, },
    endgameDenominator: { type: Number, },
    createdAt: { type: Date, default: Date.now, },
    updatedAt: { type: Date, default: Date.now, },
  },
);

const MatchSummary = mongoose.models?.MatchSummary || mongoose.model<IMatchSummary>("MatchSummary", MatchSummarySchema);

export default MatchSummary;